language: cpp
script: cmake
compiler:
  - clang
  - gcc
notifications:
  email:
    recipients:
      - tade60@freemail.hu
    on_success: always
    on_failure: always
branches:
  only:
    - master
    - coverity_scan
before_install:
  - sudo apt-get update
  - uname -a
  - free
  - cat /proc/cpuinfo
  - g++ -v
  - clang++ -v
install: sudo apt-get install libboost-dev libboost-date-time-dev libboost-thread-dev libboost-system-dev libboost-filesystem-dev	libboost-program-options-dev libboost-test-dev libusb-dev libxml2-dev valgrind
before_script: mkdir cmake-build
script:
  - cd cmake-build
  - cmake ../src -DCMAKE_BUILD_TYPE=Release -DUSE_BOOST_TEST=TRUE -DCMAKE_INSTALL_PREFIX=/usr && make -j4 && make test ARGS=-j99
  - make clean
  - cmake ../src -DCMAKE_BUILD_TYPE=Debug -DUSE_BOOST_TEST=TRUE -DCMAKE_INSTALL_PREFIX=/usr && make -j4 && make test ARGS=-j99
  - make clean

env:
  global:
   - secure: "TwkmQpkzvrzW58QB9igH+8wATcWSyW+oWkWKUkCfjjZ4zEz5WA8v1CGk3/ABA1EllvdCxcMXwvP66A8NKQYET79lQxPXBK+l9GtC2gco4M3wZ5afW+5BCnsTehQLzKqM+2CK7Zlab7RKQ4g9/X8XTjrD5gN3rmVkgz2+dNKZ/N0="

addons:
  coverity_scan:
    project:
      name: "ralovich/antpm"
      description: "Build submitted via Travis CI"
    notification_email: ralovich@in.tum.de
    build_command_prepend: "mkdir cmake-build && cd cmake-build && cmake ../src -DCMAKE_BUILD_TYPE=Debug -DUSE_BOOST_TEST=TRUE -DCMAKE_INSTALL_PREFIX=/usr && make clean"
    build_command:   "make -j4"
    branch_pattern: coverity_scan

