# -*- coding: iso-8859-2-unix -*-
env:
  global:
   - secure: "dSSIDimGn1EKLmZYntbEFlhFK344PJ16QouugG3gbWW4/fuSnQt7sboJqtD1TKDNJ7/wyzrStkkFFAgh2NqhPzajMg02HCkWF9EVKfEXORkVfr3bKPMSQ5XNFHzGhrQsF4bCrL6ZP+02u3Rm/0OpoK5G7kHCSQmnWRpKdzSZ3vg="

addons:
  coverity_scan:
    project:
      name: "ralovich/antpm"
      description: "ANT+minus Build submitted via Travis CI"
    notification_email: ralovich@in.tum.de
    build_command_prepend: "pwd && cd cmake-build && pwd && cmake ../src -DCMAKE_BUILD_TYPE=Debug -DUSE_BOOST_TEST=TRUE"
    build_command:   "make"
    branch_pattern: coverity_scan
    build_script_url: "https://raw.githubusercontent.com/ralovich/antpm/master/scripts/coverity_scan_script.sh"

language: cpp
script: cmake
compiler:
  - clang
  - gcc
notifications:
  email:
    recipients:
      - ralovich@in.tum.de
    on_success: always
    on_failure: always
branches:
  only:
    - master
    - coverity_scan
before_install:
  - sudo apt-get update
  - uname -a
  - free
  - cat /proc/cpuinfo
  - g++ -v
  - clang++ -v
install: sudo apt-get install libboost-dev libboost-date-time-dev libboost-thread-dev libboost-system-dev libboost-filesystem-dev	libboost-program-options-dev libboost-test-dev libusb-dev libxml2-dev valgrind
before_script: mkdir cmake-build
script:
  - cd cmake-build
  - cmake ../src -DCMAKE_BUILD_TYPE=Release -DUSE_BOOST_TEST=TRUE -DCMAKE_INSTALL_PREFIX=/usr && make -j4 && make test ARGS=-j99
  - make clean
  - cmake ../src -DCMAKE_BUILD_TYPE=Debug -DUSE_BOOST_TEST=TRUE -DCMAKE_INSTALL_PREFIX=/usr && make -j4 && make test ARGS=-j99
  - make clean

