# -*- coding: iso-8859-2-unix -*-
sudo: false
env:
  global:
   - secure: "I1Jdwk4mbz9YjiYEMeMwWZjrBz1oauuGyW/WNOkdq4FkfyPFQcwvU/VnefIGnXCZ7YBS6tuXY8DNQZC0CSWPusebYCKHDdTiiQlcmQ3+L/UPy5a8jABwASHTXsJtte4S5hUq+KLzzBtMmsBwMT2xWO2zskuOkq6tFIqP4N3hfag="

addons:
  coverity_scan:
    project:
      name: "ralovich/antpm"
      description: "ANT+minus Build submitted via Travis CI"
    notification_email: ralovich@in.tum.de
    build_command_prepend: "pwd && cd cmake-build && pwd && cmake ../src -DCMAKE_BUILD_TYPE=Debug -DUSE_BOOST_TEST=TRUE"
    build_command:   "make"
    branch_pattern: coverity_scan
    build_script_url: "https://raw.githubusercontent.com/ralovich/antpm/master/scripts/coverity_scan_script.sh"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - libboost-dev
    - libboost-date-time-dev
    - libboost-thread-dev
    - libboost-atomic-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libboost-test-dev
    - libusb-dev
    - libxml2-dev
    - valgrind

language: cpp
script: cmake
compiler:
  - clang
  - gcc
notifications:
  email:
    recipients:
      - ralovich@in.tum.de
    on_success: always
    on_failure: always
branches:
  only:
    - master
    - coverity_scan
before_install:
  - uname -a
  - free
  - cat /proc/cpuinfo
  - g++ -v
  - clang++ -v
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script: mkdir cmake-build
script:
  - cd cmake-build
  - cmake ../src -DCMAKE_BUILD_TYPE=Release -DUSE_BOOST_TEST=TRUE -DCMAKE_INSTALL_PREFIX=/usr && make -j4 && make test ARGS=-j99
  - make clean
  - cmake ../src -DCMAKE_BUILD_TYPE=Debug -DUSE_BOOST_TEST=TRUE -DCMAKE_INSTALL_PREFIX=/usr && make -j4 && make test ARGS=-j99
  - make clean

